#项目相关配置
mesh:
  time:
    routerUpdateDay: 1
    gatewayUpdateDay: 1
  # 文件路径 示例（Linux配置 /home/mesh/uploadPath）
  fileUpdate:
    localdir: /data/meshStatistics/uploadPath

#日志文件存放路径配置
logging:
  file:
    path: /data/meshStatistics/meshLog


# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /


# 数据源配置
spring:
  elasticsearch:
    cluster:
      name: es1
    address: 192.168.111.31
    zen:
      discovery:
        port: 9300
    port: 9200
    index:
      apIndexName: aponline
    type:
      apTypeName: messagedb

  #sftp路径
  datatransport:
    sftpdir: /data/super/301/data/
    sftp:
      name: zhhjt
      pass: zhhjt#123
      ip: 10.251.16.137
      port: 6122

  threads:
    pool:
      corePoolSize: 10